// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Lab3.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext():base()
    {
        
    }
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var connectionString = "Server=.;Database=ITIV2;Trusted_connection=true;TrustServerCertificate=true";
        optionsBuilder.UseSqlServer(connectionString);

        base.OnConfiguring(optionsBuilder);
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<InstCourse> InstCourses { get; set; }

    public virtual DbSet<Instractor> Instractors { get; set; }

    public virtual DbSet<StudCourse> StudCourses { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CrsId);

            entity.HasIndex(e => e.TopId, "IX_Courses_TopId");

            entity.Property(e => e.CrsName).HasMaxLength(50);

            entity.HasOne(d => d.Top).WithMany(p => p.Courses).HasForeignKey(d => d.TopId);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DeptId);

            entity.HasIndex(e => e.DeptManager, "IX_Departments_DeptManager");

            entity.Property(e => e.DeptDesc).HasMaxLength(100);
            entity.Property(e => e.DeptLocation).HasMaxLength(50);
            entity.Property(e => e.DeptName).HasMaxLength(50);

            entity.HasOne(d => d.DeptManagerNavigation).WithMany(p => p.Departments).HasForeignKey(d => d.DeptManager);
        });

        modelBuilder.Entity<InstCourse>(entity =>
        {
            entity.HasKey(e => new { e.InsId, e.CrsId });

            entity.HasIndex(e => e.CrsId, "IX_InstCourses_CrsId");

            entity.Property(e => e.Evaluation).HasMaxLength(50);

            entity.HasOne(d => d.Crs).WithMany(p => p.InstCourses).HasForeignKey(d => d.CrsId);

            entity.HasOne(d => d.Ins).WithMany(p => p.InstCourses).HasForeignKey(d => d.InsId);
        });

        modelBuilder.Entity<Instractor>(entity =>
        {
            entity.HasKey(e => e.InsId);

            entity.HasIndex(e => e.DeptId, "IX_Instractors_DeptId");

            entity.Property(e => e.InsDegree).HasMaxLength(50);
            entity.Property(e => e.InsName).HasMaxLength(50);
            entity.Property(e => e.Salary).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Dept).WithMany(p => p.Instractors).HasForeignKey(d => d.DeptId);
        });

        modelBuilder.Entity<StudCourse>(entity =>
        {
            entity.HasKey(e => new { e.StId, e.CrsId });

            entity.HasIndex(e => e.CrsId, "IX_StudCourses_CrsId");

            entity.HasOne(d => d.Crs).WithMany(p => p.StudCourses).HasForeignKey(d => d.CrsId);

            entity.HasOne(d => d.St).WithMany(p => p.StudCourses).HasForeignKey(d => d.StId);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StId);

            entity.HasIndex(e => e.DepartmentId, "IX_Students_DepartmentId");

            entity.HasIndex(e => e.StSuper, "IX_Students_StSuper");

            entity.Property(e => e.Address).HasMaxLength(100);
            entity.Property(e => e.Fname)
                .HasMaxLength(10)
                .HasColumnName("FName");
            entity.Property(e => e.Lname).HasColumnName("LName");

            entity.HasOne(d => d.Department).WithMany(p => p.Students).HasForeignKey(d => d.DepartmentId);

            entity.HasOne(d => d.StSuperNavigation).WithMany(p => p.InverseStSuperNavigation).HasForeignKey(d => d.StSuper);
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.TopId);

            entity.Property(e => e.TopName).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}