// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab3.Models;

public partial class Course
{
    public int CrsId { get; set; }

    public string CrsName { get; set; }

    public int? CrsDuration { get; set; }

    public int? TopId { get; set; }

    public virtual ICollection<InstCourse> InstCourses { get; set; } = new List<InstCourse>();

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();

    public virtual Topic Top { get; set; }
}