// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab3.Models;

public partial class Department
{
    public int DeptId { get; set; }

    public string DeptName { get; set; }

    public string DeptDesc { get; set; }

    public string DeptLocation { get; set; }

    public DateOnly? ManagerHireDate { get; set; }

    public int? DeptManager { get; set; }

    public virtual Instractor DeptManagerNavigation { get; set; }

    public virtual ICollection<Instractor> Instractors { get; set; } = new List<Instractor>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}