// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab3.Models;

public partial class Instractor
{
    public int InsId { get; set; }

    public string InsName { get; set; }

    public string InsDegree { get; set; }

    public decimal? Salary { get; set; }

    public int? DeptId { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<InstCourse> InstCourses { get; set; } = new List<InstCourse>();
}