// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab3.Models;

public partial class Student
{
    public int StId { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Address { get; set; }

    public int? Age { get; set; }

    public int? DepartmentId { get; set; }

    public int? StSuper { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Student> InverseStSuperNavigation { get; set; } = new List<Student>();

    public virtual Student StSuperNavigation { get; set; }

    public virtual ICollection<StudCourse> StudCourses { get; set; } = new List<StudCourse>();
}