// <auto-generated />
using System;
using Lab2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2.Entity.Course", b =>
                {
                    b.Property<int>("CrsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsId"));

                    b.Property<int?>("CrsDuration")
                        .HasColumnType("int");

                    b.Property<string>("CrsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TopId")
                        .HasColumnType("int");

                    b.HasKey("CrsId");

                    b.HasIndex("TopId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Lab2.Entity.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeptLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DeptManager")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("ManagerHireDate")
                        .HasColumnType("date");

                    b.HasKey("DeptId");

                    b.HasIndex("DeptManager");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Lab2.Entity.InstCourse", b =>
                {
                    b.Property<int>("InsId")
                        .HasColumnType("int");

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<string>("Evaluation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InsId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("InstCourses");
                });

            modelBuilder.Entity("Lab2.Entity.Instractor", b =>
                {
                    b.Property<int>("InsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsId"));

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("InsDegree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InsId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instractors");
                });

            modelBuilder.Entity("Lab2.Entity.StudCourse", b =>
                {
                    b.Property<int>("StId")
                        .HasColumnType("int");

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("StId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("StudCourses");
                });

            modelBuilder.Entity("Lab2.Entity.Student", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StId"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StSuper")
                        .HasColumnType("int");

                    b.HasKey("StId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StSuper");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Lab2.Entity.Topic", b =>
                {
                    b.Property<int>("TopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopId"));

                    b.Property<string>("TopName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TopId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Lab2.Entity.Course", b =>
                {
                    b.HasOne("Lab2.Entity.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("TopId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Lab2.Entity.Department", b =>
                {
                    b.HasOne("Lab2.Entity.Instractor", "Instractor")
                        .WithMany("Departments")
                        .HasForeignKey("DeptManager");

                    b.Navigation("Instractor");
                });

            modelBuilder.Entity("Lab2.Entity.InstCourse", b =>
                {
                    b.HasOne("Lab2.Entity.Course", "Course")
                        .WithMany("instCourses")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2.Entity.Instractor", "Instractor")
                        .WithMany("instCourses")
                        .HasForeignKey("InsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instractor");
                });

            modelBuilder.Entity("Lab2.Entity.Instractor", b =>
                {
                    b.HasOne("Lab2.Entity.Department", "Department")
                        .WithMany("Instractors")
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Lab2.Entity.StudCourse", b =>
                {
                    b.HasOne("Lab2.Entity.Course", "Course")
                        .WithMany("StudCourses")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2.Entity.Student", "Student")
                        .WithMany("StudCourses")
                        .HasForeignKey("StId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Lab2.Entity.Student", b =>
                {
                    b.HasOne("Lab2.Entity.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Lab2.Entity.Student", "StudSuper")
                        .WithMany("Students")
                        .HasForeignKey("StSuper");

                    b.Navigation("Department");

                    b.Navigation("StudSuper");
                });

            modelBuilder.Entity("Lab2.Entity.Course", b =>
                {
                    b.Navigation("StudCourses");

                    b.Navigation("instCourses");
                });

            modelBuilder.Entity("Lab2.Entity.Department", b =>
                {
                    b.Navigation("Instractors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Lab2.Entity.Instractor", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("instCourses");
                });

            modelBuilder.Entity("Lab2.Entity.Student", b =>
                {
                    b.Navigation("StudCourses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Lab2.Entity.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
